apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tk-ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticketster.com
      http:
        paths:
          # Auth Service Routes
          - path: /api/users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tk-auth-srv
                port:
                  number: 3000
          # Tickets Service Routes
          - path: /api/tickets/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tk-tickets-srv
                port:
                  number: 3000
          # Catch All Route
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tk-client-srv
                port:
                  number: 3000
