#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd ./auth
npm run lint
npm run format:fix
# npm run test:ci

cd ../client
npm run lint
# npm run format:fix
# npm run test:ci

# cd ../common
# npm run lint
# npm run format:fix
# npm run test:ci

cd ../orders
npm run lint
npm run format:fix
# npm run test:ci

cd ../tickets
npm run lint
npm run format:fix
# npm run test:ci
